### ISSUE TITLE
Unexpected error upon upload of digital pulse

### ISSUE THREAD

**Issue by cknaut** [lukingroup/pylabnet#260] opened 2021-06-30 16:56 UTC
This pulse block compilesand uploads fine:
![image](https://user-images.githubusercontent.com/4958226/124001238-6c4f5580-d9a2-11eb-932b-0123e9b01694.png)

Changing the duration of the Toptica2 pulse to 2us leads to successful compilation:

![image](https://user-images.githubusercontent.com/4958226/124001297-7a04db00-d9a2-11eb-96c0-ff270127da5a.png)

But the upload to the instrument fails:
![image](https://user-images.githubusercontent.com/4958226/124001283-75d8bd80-d9a2-11eb-964e-5e76af4c81c9.png)

**Comment by huanyanqi** [comment] 2021-07-30 20:01
Duplicate of #236 , will try to fix...

**Closed by huanyanqi** 2021-07-30 20:01 UTC
Labels: pulsemaster
